import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('Early Adopter lifecycle sends one stage-appropriate reminder and transitions cleanly', () => {
  const lifecycle = read('../../src/lib/early-adopter-lifecycle.ts')
  const cronRoute = read('../../src/app/api/cron/early-adopter/route.ts')
  const vercel = read('../../vercel.json')

  assert.match(lifecycle, /\.in\('status', \['active', 'grace', 'finishing'\]\)/)
  assert.match(lifecycle, /status: 'completed'/)
  assert.match(lifecycle, /status: 'removed'/)
  assert.match(lifecycle, /notice_type: noticeType/)
  assert.match(lifecycle, /claimError\?\.code === '23505'/)
  assert.match(lifecycle, /grace_final_week'[\s\S]*else if[\s\S]*grace_month_one'[\s\S]*else if[\s\S]*feedback_due'[\s\S]*else if[\s\S]*feedback_window_open'/)
  assert.match(cronRoute, /processEarlyAdopterLifecycle/)
  assert.match(cronRoute, /verifyBearerSecret/)
  assert.match(vercel, /api\/cron\/early-adopter/)
})

test('Early Adopter service emails explain claiming, rewards, deadlines, grace, completion, and data safety', () => {
  const notifications = read('../../src/lib/notifications.ts')
  const joinRoute = read('../../src/app/api/marketing/leads/route.ts')

  assert.match(notifications, /notifyEarlyAdopterWelcome/)
  assert.match(notifications, /place is ready to claim/i)
  assert.match(notifications, /Email submission alone does not consume a programme place/)
  assert.match(notifications, /Pro activates automatically/)
  assert.match(notifications, /claim Pro month \$\{nextMonth\}/)
  assert.match(notifications, /two-month grace period/i)
  assert.match(notifications, /Final week to keep your Early Adopter place/)
  assert.match(notifications, /projects and feedback are never deleted/i)
  assert.match(notifications, /complet(?:ed|ing) all 12 months/i)
  assert.match(joinRoute, /membership\.alreadyJoined/)
  assert.match(joinRoute, /notifyEarlyAdopterWelcome\(\{ email \}\)/)
})

test('password, magic-link, OAuth, and already signed-in enrolments all link the programme claim', () => {
  const authPage = read('../../src/app/auth/page.tsx')
  const callback = read('../../src/app/auth/callback/route.ts')
  const activateRoute = read('../../src/app/api/early-adopter/activate/route.ts')
  const joinRoute = read('../../src/app/api/marketing/leads/route.ts')

  assert.match(authPage, /fetch\('\/api\/early-adopter\/activate', \{ method: 'POST' \}\)/)
  assert.match(callback, /activateEarlyAdopterMembership/)
  assert.match(callback, /user\.email && user\.email_confirmed_at/)
  assert.match(activateRoute, /supabase\.auth\.getUser\(\)/)
  assert.match(activateRoute, /user\.email_confirmed_at/)
  assert.match(activateRoute, /activateEarlyAdopterMembership\(user\.id, user\.email\)/)
  assert.match(joinRoute, /user\.email\.toLowerCase\(\) === email/)
  assert.match(joinRoute, /hasVerifiedMatchingAccount/)
})

test('programme onboarding cannot be dismissed and activates Pro only after the guided tour', () => {
  const tour = read('../../src/components/product-tour.tsx')
  const layout = read('../../src/app/(dashboard)/layout.tsx')
  const sidebar = read('../../src/components/sidebar.tsx')
  const celebration = read('../../src/components/pro-activation-celebration.tsx')
  const feedbackForm = read('../../src/app/(dashboard)/early-adopter/feedback-form.tsx')
  const billingClient = read('../../src/app/(dashboard)/billing/billing-client.tsx')
  const onboardingRoute = read('../../src/app/api/early-adopter/onboarding/route.ts')
  const migration = read('../../../../sql/065_early_adopter_programme.sql')
  const claimMigration = read('../../../../sql/066_claim_early_adopter_seats_on_activation.sql')

  assert.match(tour, /if \(required\) return/)
  assert.match(tour, /Complete the guided tour to unlock Pro/)
  assert.match(tour, /Learn feedbacks\.dev with a guided tour/)
  assert.match(tour, /Start product tour/)
  assert.match(tour, /Take it now or come back later from Product tour in the account menu/)
  assert.match(tour, /Begin guided tour/)
  assert.match(tour, /cannot be skipped/)
  assert.match(tour, /Finish and activate Pro/)
  assert.match(tour, /Pro activates at the end/)
  assert.match(tour, /required && stepIndex === 0/)
  assert.equal((tour.match(/Complete every step of this guided onboarding/g) || []).length, 1)
  assert.match(layout, /required=\{requiredEarlyAdopterOnboarding\}/)
  assert.doesNotMatch(layout, /EarlyAdopterBanner/)
  assert.match(sidebar, /Early Adopter Programme/)
  assert.match(sidebar, /early-adopter-sidebar-item-attention/)
  assert.match(celebration, /const HOLD_MS = 3_000/)
  assert.match(celebration, /const DISPLAY_MS = HOLD_MS \+ FLIGHT_MS/)
  assert.match(celebration, /data-pro-celebration-phase=\{phase\}/)
  assert.match(celebration, /loadedAssets !== 3/)
  assert.match(celebration, /data-pro-celebration-ready=\{assetsReady/)
  assert.match(celebration, /Welcome to Pro\./)
  assert.match(celebration, /feedbacks\.dev_pro_monthly\.svg/)
  assert.doesNotMatch(celebration, /feedbacks\.dev_pro_monthly\.png/)
  assert.doesNotMatch(tour, /announceProActivation/)
  assert.doesNotMatch(feedbackForm, /announceProActivation/)
  assert.doesNotMatch(billingClient, /announceProActivation/)
  assert.doesNotMatch(sidebar, /proBrandSuppressed/)
  assert.match(layout, /shouldOfferStandardOnboarding/)
  assert.match(layout, /!preferences\.productTourCompletedAt/)
  assert.match(layout, /!preferences\.productTourDismissedAt/)
  assert.match(tour, /programmeResponse = required/)
  assert.match(onboardingRoute, /Finish every tour step before activating Pro/)
  assert.match(migration, /productTourCompletedAt/)
  assert.match(claimMigration, /alter column seat_number drop not null/i)
  assert.match(claimMigration, /where onboarding_completed_at is null/i)
  assert.match(claimMigration, /generate_series\(1, v_program\.capacity\)/i)
  assert.match(claimMigration, /set seat_number = v_next_seat/i)
  assert.match(claimMigration, /'reason', 'capacity_full'/i)
})

test('programme theme follows the visitor through enrolment and sign-in', () => {
  const rootLayout = read('../../src/app/layout.tsx')
  const programmePage = read('../../src/app/early-access/page.tsx')
  const leadForm = read('../../src/app/early-access/lead-form.tsx')
  const authPage = read('../../src/app/auth/page.tsx')

  assert.match(rootLayout, /<head>[\s\S]*appearanceSyncScript[\s\S]*<body/)
  assert.match(programmePage, /bg-background/)
  assert.doesNotMatch(programmePage, /bg-neutral-950/)
  assert.match(leadForm, /authParams\.set\('appearance', appearance\)/)
  assert.match(authPage, /setTheme\(requestedAppearance\)/)
})

test('programme marketing keeps places scarce and protects member pricing', () => {
  const landing = read('../../src/app/page.tsx')
  const mobileMenu = read('../../src/components/landing-mobile-menu.tsx')
  const programmePage = read('../../src/app/early-access/page.tsx')
  const leadForm = read('../../src/app/early-access/lead-form.tsx')
  const terms = read('../../src/app/terms/page.tsx')

  assert.match(landing, /Join the Early Adopter Programme/)
  assert.match(mobileMenu, /Join the Early Adopter Programme/)
  assert.match(programmePage, /Only 100 places/)
  assert.match(programmePage, /Five years of price protection/)
  assert.match(programmePage, /grandfathered for at least five years/)
  assert.match(programmePage, /place is counted only after guided onboarding/i)
  assert.match(leadForm, /Your place is ready to claim/)
  assert.match(leadForm, /Email submission alone does not use one of the 100 places/)
  assert.match(terms, /maximum Pro list price for at least five years/)
  assert.doesNotMatch(programmePage, /accepted automatically/i)
  assert.doesNotMatch(leadForm, /accepted automatically/i)
})

test('programme claims are CAPTCHA-verified before any membership or email side effect', () => {
  const leadForm = read('../../src/app/early-access/lead-form.tsx')
  const joinRoute = read('../../src/app/api/marketing/leads/route.ts')
  const captcha = read('../../src/lib/captcha.ts')

  assert.match(leadForm, /action="early_adopter_claim"/)
  assert.match(leadForm, /captchaToken/)
  assert.match(leadForm, /setCaptchaResetKey/)
  assert.match(joinRoute, /verifyEarlyAdopterCaptcha\(request, result\.data\.captchaToken\)/)
  assert.ok(joinRoute.indexOf('verifyEarlyAdopterCaptcha') < joinRoute.indexOf('joinEarlyAdopterProgramme(email)'))
  assert.match(captcha, /process\.env\.NODE_ENV !== 'production'/)
  assert.match(captcha, /reason: 'misconfigured'/)
  assert.match(captcha, /body\.set\('remoteip', remoteIp\)/)
  assert.match(captcha, /body\.set\('sitekey', siteKey\)/)
  assert.match(captcha, /result\.action === expectedAction/)
})
