import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('landing page explains both sides of the feedback loop and keeps the install-once architecture', () => {
  const source = read('../../src/app/page.tsx')
  const demo = read('../../src/components/landing-hero-demo.tsx')
  const install = read('../../src/components/landing-install-story.tsx')
  const feedback = read('../../src/components/landing-feedback-story.tsx')
  const connections = read('../../src/components/landing-connections-story.tsx')

  assert.match(source, /Find what users need\./)
  assert.match(source, /Show what you fixed\./)
  assert.match(source, /Add one feedback button to your app/)
  assert.match(source, /Add feedback to your app in three steps\./)
  assert.match(source, /See the report\. Fix it\. Tell the user\./)
  assert.match(source, /Your public project key cannot open your inbox\./)
  assert.match(source, /What you need to know before installing\./)
  assert.match(source, /Under 20KB gzip/)
  assert.match(source, /Private feedback media/)
  assert.match(source, /Install in under 10 minutes/)
  assert.match(source, /vibe-coded app/)
  assert.match(source, /latest deploy/)
  assert.match(source, /Three customers ask for the same small feature/)
  assert.match(source, /A client reports a bug/)
  assert.doesNotMatch(source, /The product loop/)
  assert.doesNotMatch(source, /Designed for developer trust/)
  assert.match(demo, /Orbit/)
  assert.match(demo, /Paste one snippet/)
  assert.match(demo, /landing-demo-tab-label/)
  assert.match(demo, /landing-demo-tab-detail/)
  assert.match(demo, /landing-demo-tab-icon-active/)
  assert.match(demo, /User sends context/)
  assert.match(demo, /Your team acts/)
  assert.match(demo, /User sees the fix/)
  assert.match(demo, /Screenshot/)
  assert.match(demo, /prefers-reduced-motion/)
  assert.doesNotMatch(demo, /setInterval/)
  assert.match(demo, /setTimeout/)
  assert.match(install, /Copy the snippet/)
  assert.match(install, /Send one test/)
  assert.match(install, /Customize later/)
  assert.match(install, /No private credential enters the browser/)
  assert.match(feedback, /A user tells you/)
  assert.match(feedback, /Your team fixes it/)
  assert.match(feedback, /Users see the fix/)
  assert.match(connections, /Slack/)
  assert.match(connections, /GitHub/)
  assert.match(connections, /Discord/)
  assert.match(connections, /API or MCP/)
  assert.match(connections, /public ideas page/i)
  assert.match(source, /More projects and feedback/)
  assert.doesNotMatch(source, /Unlimited projects/)
  assert.match(source, /generateInstallSnippets/)
  assert.match(source, /LandingHeroDemo/)
  assert.match(source, /LandingFeedbackStory/)
  assert.match(source, /LandingInstallStory/)
  assert.doesNotMatch(source, /WidgetDemo/)
  assert.doesNotMatch(source, /createServerSupabase/)
  assert.doesNotMatch(source, /userbase|Collecting user feedbacks/)
})

test('marketing routes expose a crawlable acquisition foundation without indexing private workspaces', () => {
  const layout = read('../../src/app/layout.tsx')
  const landing = read('../../src/app/page.tsx')
  const robots = read('../../src/app/robots.ts')
  const sitemap = read('../../src/app/sitemap.ts')
  const openGraph = read('../../src/app/opengraph-image.tsx')
  const site = read('../../src/lib/site.ts')

  assert.match(site, /SITE_ORIGIN = 'https:\/\/www\.feedbacks\.dev'/)
  assert.match(layout, /metadataBase: new URL\(SITE_ORIGIN\)/)
  assert.match(landing, /SoftwareApplication/)
  assert.match(landing, /summary_large_image/)
  assert.match(landing, /alternates: \{ canonical: '\/' \}/)
  assert.match(robots, /sitemap: `\$\{SITE_ORIGIN\}\/sitemap\.xml`/)
  assert.match(robots, /'\/dashboard'/)
  assert.match(robots, /'\/api\/'/)
  assert.match(sitemap, /DOCS_PAGES/)
  assert.match(sitemap, /`\$\{SITE_ORIGIN\}\/boards`/)
  assert.match(openGraph, /ImageResponse/)
  assert.match(openGraph, /Find what users need\./)
  assert.match(landing, /\/early-access/)
})

test('first-run and public feedback screens keep optional work out of the main path', () => {
  const newProject = read('../../src/app/(dashboard)/projects/new/page.tsx')
  const inbox = read('../../src/app/(dashboard)/feedback/page.tsx')
  const publicForm = read('../../src/components/boards/BoardSubmitForm.tsx')

  assert.match(newProject, /Name your app or website/)
  assert.match(newProject, /Add project details/)
  assert.match(newProject, /Create project and get the snippet/)
  assert.doesNotMatch(newProject, /Choose a different first goal/)
  assert.doesNotMatch(newProject, /What happens next/)
  assert.match(inbox, /Review new messages and move the useful signal forward\./)
  assert.match(inbox, /showMoreFilters/)
  assert.match(publicForm, /What do you need\?/)
  assert.match(publicForm, /className="sr-only"/)
})

test('project creation checks plan limits before writing a project', () => {
  const route = read('../../src/app/api/projects/route.ts')
  const billing = read('../../src/lib/billing.ts')
  const plans = read('../../../shared/src/plans.ts')

  assert.match(plans, /projectLimit: 2/)
  assert.match(route, /assertCanCreateProject/)
  assert.ok(route.indexOf('assertCanCreateProject') < route.indexOf("from('projects').insert"))
  assert.match(route, /status: 403/)
  assert.match(billing, /project_limit_reached/)
})

test('navigation gives product updates user context instead of an ambiguous release-notes label', () => {
  const sidebar = read('../../src/components/sidebar.tsx')
  const projectHome = read('../../src/app/(dashboard)/projects/[id]/project-home.tsx')
  const updatesOnboarding = read('../../src/components/product-updates/UpdatesOnboarding.tsx')

  assert.match(sidebar, /Updates for users/)
  assert.match(projectHome, /Product updates/)
  assert.match(updatesOnboarding, /useState<Choice>\(["']updates["']\)/)
  assert.doesNotMatch(updatesOnboarding, /localStorage/)
  assert.doesNotMatch(sidebar, /label: 'Release notes'/)
})

test('release note editor exposes recovery and destructive actions without vague page naming', () => {
  const editor = read('../../src/components/product-updates/ProductUpdatesTab.tsx')
  const imageEditor = read('../../src/components/product-updates/ProductUpdateImageEditor.tsx')

  assert.match(editor, /Edit release note/)
  assert.doesNotMatch(editor, /Edit product update/)
  assert.match(editor, /Reload saved version/)
  assert.match(editor, /Saved version recovery/)
  assert.match(editor, /Editing paused for safety/)
  assert.match(editor, /fixed bottom-/)
  assert.match(editor, /requestWithFreshVersion/)
  assert.match(editor, /recoveredFromConflict/)
  assert.match(editor, /Choose image/)
  assert.match(editor, /Replace image/)
  assert.match(editor, /imageInputRef\.current\?\.click/)
  assert.match(editor, /imageUrl: result\.update\.imageUrl/)
  assert.match(editor, /pendingImagePreviewUrl/)
  assert.match(editor, /Previewing unsaved crop/)
  assert.match(imageEditor, /onPreviewChange\(nextPreviewUrl\)/)
  assert.match(imageEditor, /URL\.revokeObjectURL/)
  assert.match(editor, /Delete release note/)
  assert.match(editor, /Remove image/)
  assert.match(editor, /Editing does not re-announce this release note/)
  assert.match(editor, /Publishing creates this release note&apos;s announcement identity/)
  assert.match(editor, /Save correction/)
  assert.match(editor, /Confirm publish/)
  assert.match(editor, /ProductUpdateVisibilityToggle/)
  assert.match(editor, /hydratedUpdateRef/)
  assert.match(imageEditor, /Drag inside the frame to move it/)
  assert.match(imageEditor, /Resize from top left/)
  assert.match(imageEditor, /resizeProductUpdateCropFromCorner/)
  assert.doesNotMatch(imageEditor, /Horizontal crop position/)
})

test('feedback form editor refreshes stale baselines and exposes explicit recovery', () => {
  const editor = read('../../src/app/(dashboard)/projects/[id]/customize-tab.tsx')

  assert.match(editor, /loadLatestProject/)
  assert.match(editor, /latestFingerprint === draftFingerprint/)
  assert.match(editor, /latestFingerprint === savedFingerprint/)
  assert.match(editor, /Feedback form already saved/)
  assert.match(editor, /Reload saved settings/)
  assert.match(editor, /The existing host becomes the inline form/)
  assert.match(editor, /Connect feedback to your own button/)
  assert.match(editor, /Trigger selector/)
  assert.match(editor, /No code change needed/)
})

test('dense dashboard forms use clear tonal sections instead of one flat canvas', () => {
  const section = read('../../src/components/ui/workspace-section.tsx')
  const boardIdentity = read('../../src/components/board-settings/BoardIdentitySection.tsx')
  const boardVisibility = read('../../src/components/board-settings/BoardVisibilitySection.tsx')
  const inbox = read('../../src/app/(dashboard)/feedback/page.tsx')

  assert.match(section, /rounded-lg border bg-card/)
  assert.match(section, /border-b bg-surface-raised\/70/)
  assert.match(boardIdentity, /WorkspaceSection/)
  assert.match(boardVisibility, /WorkspaceSection/)
  assert.match(inbox, /rounded-lg border bg-card/)
})

test('sidebar exposes a stable Home destination and groups project work by user intent', () => {
  const sidebar = read('../../src/components/sidebar.tsx')

  assert.match(sidebar, /label: 'Home'/)
  assert.match(sidebar, /label: 'Collect'/)
  assert.match(sidebar, /label: 'Share with users'/)
  assert.match(sidebar, /label: 'Connect'/)
  assert.match(sidebar, /Public feedback board/)
  assert.match(sidebar, /label: 'Feedback form', icon: ClipboardPenLine/)
  assert.match(sidebar, /label: 'Feedback inbox', icon: Inbox/)
  assert.doesNotMatch(sidebar, /label: 'Overview'/)
  assert.doesNotMatch(sidebar, /projectTab: 'home'/)
  assert.match(sidebar, /project-required\?feature=/)
  assert.match(sidebar, /label: 'Invite friends'/)
  assert.ok(sidebar.indexOf('aria-controls="mobile-navigation-drawer"') < sidebar.indexOf('<BrandWordmark', sidebar.indexOf('Mobile top bar')))
})

test('sign-in stays concise while showing the rotating use-case carousel', () => {
  const source = read('../../src/app/auth/page.tsx')
  const carousel = read('../../src/components/auth-use-case-carousel.tsx')

  assert.match(source, /Sign in or create an account/)
  assert.match(source, /New accounts start on the Free plan/)
  assert.match(source, /Back to home/)
  assert.match(source, /SITE_ORIGIN/)
  assert.match(source, /marketingHomeHref/)
  assert.match(source, /<AuthUseCaseCarousel/)
  assert.match(source, /compact displayMode="mobile"/)
  assert.doesNotMatch(source, /Hear what matters/)
  assert.doesNotMatch(source, /Feedback that earns its place/)
  assert.match(carousel, /A user found a bug you cannot reproduce/)
  assert.match(carousel, /Three users asked for the same feature/)
  assert.match(carousel, /Your AI-built app changes every week/)
  assert.doesNotMatch(carousel, /benefits:/)
  assert.doesNotMatch(carousel, /Built for the whole feedback loop/)
  assert.match(carousel, /4_800/)
  assert.match(carousel, /onClickCapture/)
  assert.doesNotMatch(carousel, /onMouseEnter/)
  assert.match(carousel, /Show previous use case/)
  assert.match(carousel, /Show next use case/)
  assert.match(carousel, /Stop automatic story rotation/)
  assert.match(carousel, /Start automatic story rotation/)
  assert.match(carousel, /visibilitychange/)
  assert.match(carousel, /aria-roledescription="slide"/)
  assert.match(carousel, /auth-card-signal/)
  assert.match(carousel, /prefers-reduced-motion/)
  assert.doesNotMatch(source, /data-api-url/)
})

test('marketing hero and workspace states share the new motion and texture language', () => {
  const css = read('../../src/app/globals.css')
  const emptyState = read('../../src/components/ui/empty-state.tsx')
  const layout = read('../../src/app/(dashboard)/layout.tsx')

  assert.match(css, /--ease-spring:/)
  assert.match(css, /@keyframes hero-color-breathe/)
  assert.match(css, /feTurbulence/)
  assert.match(css, /\.auth-story-pane::after/)
  assert.match(css, /\.dark \.auth-story-pane::after/)
  assert.match(css, /auth-noise/)
  assert.match(css, /mix-blend-mode: soft-light/)
  assert.match(css, /\.auth-card-signal-disc/)
  assert.match(css, /\.workspace-route-enter/)
  assert.match(css, /prefers-reduced-motion/)
  assert.match(emptyState, /workspace-empty-state/)
  assert.match(layout, /key=\{pathname\}/)
})

test('settings reuses a private system project for product feedback and updates', () => {
  const settings = read('../../src/app/(dashboard)/settings/page.tsx')
  const panel = read('../../src/components/product-feedback-panel.tsx')
  const route = read('../../src/app/api/product-feedback/route.ts')
  const migration = read('../../../../sql/058_internal_product_feedback_project.sql')

  assert.match(settings, /<ProductFeedbackPanel/)
  assert.match(panel, /Suggestion/)
  assert.match(panel, /Problem/)
  assert.match(panel, /Updates from us/)
  assert.match(route, /getUser\(\)/)
  assert.match(route, /checkRateLimit\(request, 'product-feedback', 5, 10, user\.id\)/)
  assert.match(route, /is_public: false/)
  assert.match(route, /\.eq\('status', 'published'\)/)
  assert.match(migration, /drsyedirfan93@gmail\.com/i)
  assert.match(migration, /internal_feedback_project', true/i)
  assert.match(migration, /api_key,\s+api_key_hash,\s+api_key_last_four/i)
})

test('downgraded accounts keep runtime feature limits, not just dashboard gates', () => {
  const feedbackRoute = read('../../src/app/api/feedback/route.ts')
  const v1Route = read('../../src/app/api/v1/feedback/route.ts')
  const delivery = read('../../src/lib/webhook-delivery.ts')
  const bootstrap = read('../../src/app/api/widget/bootstrap/route.ts')
  const updates = read('../../src/app/api/widget/updates/route.ts')

  assert.match(feedbackRoute, /webhookEndpointLimit/)
  assert.match(v1Route, /webhookEndpointLimit/)
  assert.match(delivery, /endpointLimit/)
  assert.match(delivery, /enabledEndpointCount < endpointLimit/)
  assert.match(bootstrap, /productUpdateActiveLimit/)
  assert.match(updates, /productUpdateActiveLimit/)
})

test('widget attribution is conspicuous, linked, and controlled by server entitlements', () => {
  const widget = read('../../../widget/src/widget.ts')
  const styles = read('../../../widget/src/styles.css')
  const bootstrap = read('../../src/app/api/widget/bootstrap/route.ts')

  assert.match(widget, /https:\/\/www\.feedbacks\.dev\/\?utm_source=widget&utm_medium=powered_by/)
  assert.match(widget, /rel="noopener noreferrer"/)
  assert.match(styles, /\.fb-powered span \{[\s\S]*font-weight: 600/)
  assert.match(styles, /\.fb-powered a \{[\s\S]*color: var\(--fb-primary/)
  assert.match(styles, /font-weight: 800/)
  assert.match(bootstrap, /showPoweredBy: !billing\.entitlements\.customBranding/)
})

test('theme tokens use perceptual OKLCH colors in both themes', () => {
  const css = read('../../src/app/globals.css')
  const tailwind = read('../../tailwind.config.cjs')

  assert.match(css, /--background: 0\.968/)
  assert.match(css, /\.dark[\s\S]*--background: 0\.115/)
  assert.match(css, /\.dark[\s\S]*--surface-raised: 0\.305/)
  assert.match(css, /\.dark[\s\S]*--surface-soft: 0\.255/)
  assert.match(css, /\.dark[\s\S]*--surface-inset: 0\.165/)
  assert.match(css, /\.dark[\s\S]*--card: 0\.225/)
  assert.match(css, /\[class~="shadow-\[var\(--shadow-card\)\]"\]/)
  assert.match(css, /--surface-sidebar:/)
  assert.match(css, /--surface-selected:/)
  assert.match(tailwind, /surface:\s*\{/)
  assert.match(tailwind, /oklch\(var\(--primary\)/)
  assert.doesNotMatch(tailwind, /hsl\(var\(--primary\)/)
})

test('Windows 98 is a complete selectable appearance across product and public surfaces', () => {
  const css = read('../../src/app/globals.css')
  const layout = read('../../src/app/layout.tsx')
  const toggle = read('../../src/components/theme-toggle.tsx')
  const publicControl = read('../../src/components/public-theme-control.tsx')
  const landing = read('../../src/app/page.tsx')
  const landingStory = read('../../src/components/landing-feedback-story.tsx')
  const settings = read('../../src/app/(dashboard)/settings/page.tsx')

  assert.match(layout, /themes=\{\['light', 'dark', 'windows98'\]\}/)
  assert.match(layout, /defaultTheme="system"/)
  assert.match(toggle, /value: 'windows98', label: 'Windows 98'/)
  assert.match(toggle, /role="radiogroup"/)
  assert.match(settings, /\['windows98', 'Windows 98'\]/)
  assert.match(publicControl, /<ThemeToggle collapsed \/>/)
  assert.match(publicControl, /pathname === '\/'/)
  assert.match(landing, /<ThemeToggle landing \/>/)
  assert.match(toggle, /option\.value !== 'system'/)
  assert.match(toggle, /landing-theme-option-98/)
  assert.match(toggle, /function Windows98Mark/)
  assert.match(toggle, />Windows<\/span>/)
  assert.match(toggle, />98<\/span>/)
  assert.equal(toggle.match(/<Windows98Mark \/>/g)?.length, 3)
  assert.match(landingStory, /landing-story-step-label/)
  assert.match(css, /\.windows98 \.landing-story-step-label/)
  assert.match(css, /\.windows98 \.landing-demo-tab-label/)
  assert.match(css, /\.windows98 \.landing-demo-tab-detail/)
  assert.match(css, /\.windows98 \.landing-demo-tab-icon-active/)
  assert.match(css, /@keyframes landing-theme-98-shine/)
  assert.match(css, /\.windows98 \{/)
  assert.match(css, /--win98-raised:/)
  assert.match(css, /\.windows98 \.dashboard-shell/)
  assert.match(css, /\.windows98 \.landing-hero/)
  assert.match(css, /\.windows98 \.docs-content/)
  assert.match(css, /\.windows98 \.public-board-shell/)
  assert.match(css, /\.windows98 input/)
  assert.match(css, /\.windows98 table/)
})

test('authenticated workspaces use page headers, section panels, and progressive disclosure', () => {
  const card = read('../../src/components/ui/card.tsx')
  const install = read('../../src/app/(dashboard)/projects/[id]/install-tab.tsx')
  const projectHome = read('../../src/app/(dashboard)/projects/[id]/project-home.tsx')
  const customize = read('../../src/app/(dashboard)/projects/[id]/customize-tab.tsx')
  const verify = read('../../src/app/(dashboard)/projects/[id]/project-verify-client.tsx')

  assert.match(card, /rounded-lg border border-border bg-card/)
  assert.match(card, /border-b bg-surface-raised\/70/)
  assert.match(card, /shadow-\[var\(--shadow-card\)\]/)
  assert.match(install, /title="Choose your stack"/)
  assert.match(install, /dataTour="install-snippet"/)
  assert.match(install, /bg-surface-inset/)
  assert.match(install, /bg-surface-soft/)
  assert.match(install, /bg-surface-selected/)
  assert.match(install, /Connection details/)
  assert.match(projectHome, /<PageHeader/)
  assert.match(projectHome, /<SectionPanel/)
  assert.match(customize, /Optional fields and protection/)
  assert.match(verify, /<PageHeader/)
})

test('public docs use the stable canonical embed and remote customization language', () => {
  const source = read('../../src/lib/docs-content.ts')

  assert.match(source, /data-feedbacks-host/)
  assert.match(source, /data-project=/)
  assert.match(source, /Customize remotely/)
  assert.match(source, /installed snippet stays stable/)
  assert.doesNotMatch(source, /data-api-url/)
  assert.doesNotMatch(source, /data-config-version/)
})

test('public board directory owns a main landmark without nesting one in the dashboard', () => {
  const directorySurface = read('../../src/app/boards/board-directory-surface.tsx')

  assert.match(directorySurface, /const Root = dashboard \? 'div' : 'main'/)
  assert.match(directorySurface, /<Root/)
  assert.match(directorySurface, /<\/Root>/)
})

test('forms identify failed fields and public interactions avoid blocking browser alerts', () => {
  const input = read('../../src/components/ui/input.tsx')
  const textarea = read('../../src/components/ui/textarea.tsx')
  const newProject = read('../../src/app/(dashboard)/projects/new/page.tsx')
  const projectRoute = read('../../src/app/api/projects/route.ts')
  const boardSubmit = read('../../src/components/boards/BoardSubmitForm.tsx')
  const boardSubmitRoute = read('../../src/app/api/boards/[slug]/submit/route.ts')
  const publicBoard = read('../../src/app/p/[slug]/public-board.tsx')

  assert.match(input, /aria-\[invalid=true\]:border-destructive/)
  assert.match(textarea, /aria-\[invalid=true\]:border-destructive/)
  assert.match(newProject, /project-name-error/)
  assert.match(projectRoute, /fieldErrors: \{ name:/)
  assert.match(boardSubmit, /board-post-email-error/)
  assert.match(boardSubmitRoute, /fieldErrors: \{ email:/)
  assert.doesNotMatch(publicBoard, /window\.alert/)
  assert.match(publicBoard, /aria-live="assertive"/)
})
