import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('tracked project files do not contain em dashes', () => {
  const repositoryRoot = fileURLToPath(new URL('../../../../', import.meta.url))
  const trackedFiles = execFileSync('git', ['ls-files', '-z'], {
    cwd: repositoryRoot,
    encoding: 'utf8',
  }).split('\0').filter(Boolean)
  const literalDash = String.fromCodePoint(0x2014)
  const escapedDash = ['\\', 'u2014'].join('')
  const htmlDash = /&(?:mdash|#8212|#x2014);/i

  for (const file of trackedFiles) {
    const absolutePath = join(repositoryRoot, file)
    if (!existsSync(absolutePath)) continue
    const contents = readFileSync(absolutePath)
    if (contents.includes(0)) continue

    const text = contents.toString('utf8')
    assert.equal(text.includes(literalDash), false, `${file} contains a literal em dash`)
    assert.equal(text.includes(escapedDash), false, `${file} contains an escaped em dash`)
    assert.equal(htmlDash.test(text), false, `${file} contains an HTML em dash`)
  }
})

test('landing page explains both sides of the feedback loop and keeps the install-once architecture', () => {
  const source = read('../../src/app/page.tsx')
  const hero = read('../../src/components/landing-try-widget-hero.tsx')
  const stories = read('../../src/components/landing-product-stories.tsx')
  const install = read('../../src/components/landing-vibe-install.tsx')
  const backToTop = read('../../src/components/landing-back-to-top.tsx')
  const css = read('../../src/app/globals.css')

  assert.match(hero, /Show<\/span>, don&apos;t tell/)
  assert.match(hero, /Your users will press this button/)
  assert.match(hero, /Send feedback/)
  assert.match(hero, /Page \+ browser context included/)
  assert.match(hero, /Feedback received/)
  assert.match(hero, /useReducedMotion/)
  assert.match(hero, /landing-callout-arrowhead/)
  assert.match(hero, /markerUnits="userSpaceOnUse"/)
  assert.match(hero, /topLeftTarget/)
  assert.match(hero, /bottomRightTarget/)
  assert.doesNotMatch(hero, /const leftTarget/)
  assert.match(hero, /ResizeObserver/)
  assert.match(hero, /Scroll below when ready/)
  assert.match(hero, /The Best Addition to Your Website\/App\/SaaS ever/)
  assert.match(hero, /Scroll below to learn more/)
  assert.match(hero, /const \[phase, setPhase\] = React\.useState<DemoPhase>\('idle'\)/)
  assert.match(hero, /const completed = phase === 'complete'/)
  assert.match(hero, /setPhase\('complete'\)/)
  assert.match(hero, /const easeInOutCubic/)
  assert.match(hero, /const peekTop = heroTop \+ \(productTop - heroTop\) \* 0\.5/)
  assert.match(hero, /animateWindowScroll\(peekTop, 1200, signal\)/)
  assert.match(hero, /product\.classList\.add\('landing-reveal-prepared'\)/)
  assert.match(hero, /product\.dataset\.visible = 'true'/)
  assert.match(hero, /preparedProduct\?\.classList\.remove\('landing-reveal-prepared'\)/)
  assert.match(hero, /waitForMotion\(320, signal\)/)
  assert.match(hero, /animateWindowScroll\(heroTop, 1100, signal\)/)
  assert.match(hero, /window\.addEventListener\('wheel', cancelMotion/)
  assert.match(hero, /exit=\{\{ opacity: 0, transition: \{ duration: 0 \} \}\}/)
  assert.doesNotMatch(hero, /setOpen|setSubmitted|setCompleted/)
  assert.match(hero, /landing-post-demo-mascot/)
  assert.match(hero, /landing-tone-hero/)
  assert.doesNotMatch(hero, /LandingBackgroundBeams|landing-try-halo/)
  assert.match(hero, /landing-try-cta-default/)
  assert.match(hero, /textPath/)
  assert.match(stories, /Your customer sends feedback/)
  assert.match(stories, /You receive the full picture/)
  assert.match(stories, /The right tool gets the next action/)
  assert.match(stories, /Context included/)
  assert.match(stories, /Ready to act/)
  assert.match(stories, /Every report arrives with evidence/)
  assert.match(stories, /feedbacks\.dev dashboard/)
  assert.match(stories, /Search feedback…/)
  assert.match(stories, /Select all on this page/)
  assert.match(stories, /More filters/)
  assert.match(stories, /landing-triage-sidebar/)
  assert.match(stories, /Tell customers what shipped/)
  assert.match(stories, /Keep decisions visible/)
  assert.doesNotMatch(stories, /From message to shipped fix|Context without interrogation|Inside feedbacks\.dev|Close the loop/)
  assert.match(stories, /feedbacks\.dev\/p\/acme-app/)
  assert.doesNotMatch(stories, /ACME Corp|Preparing export|Export report/)
  assert.match(install, /Dashboard-generated snippet/)
  assert.match(install, /bg-\[#e7ebe5\]/)
  assert.match(install, /Keep the stable embed unchanged/)
  assert.match(install, /Agent brief/)
  assert.match(css, /overflow-anchor: none/)
  assert.match(css, /max-height: calc\(100svh - 11rem\)/)
  assert.match(css, /\.landing-try-stage:not\(\.landing-try-stage-open\)[\s\S]*min-height: clamp\(11\.5rem, 31svh, 14rem\)/)
  assert.match(css, /\.landing-try-cta-default/)
  assert.match(css, /--landing-slate-section:[\s\S]*radial-gradient[\s\S]*radial-gradient[\s\S]*radial-gradient[\s\S]*linear-gradient/)
  assert.match(css, /--landing-canvas:/)
  assert.match(css, /\.landing-atmosphere-section/)
  assert.match(css, /\.landing-tone-cool/)
  assert.match(css, /\.landing-tone-final/)
  assert.match(css, /prefers-reduced-motion: reduce/)
  assert.doesNotMatch(css, /landing-background-beams|landing-beam-energy-paths|landing-try-halo/)
  assert.match(css, /\.landing-flow-pill/)
  assert.doesNotMatch(css, /\.landing-flow-connector \.landing-flow-line[\s\S]*animation-name/)
  assert.match(css, /content-visibility: auto/)
  assert.match(css, /section\.landing-reveal-prepared[\s\S]*content-visibility: visible/)
  assert.match(css, /\.landing-reveal\.landing-reveal-prepared[\s\S]*transition: none/)
  assert.match(css, /\.windows98 \.win98-chrome/)
  assert.doesNotMatch(source, /Win98Chrome|win98-section-window/)
  assert.doesNotMatch(stories, /Win98Chrome|win98-section-window/)
  assert.doesNotMatch(css, /content: "feedbacks\.dev - Interactive demo"/)
  assert.match(css, /\.windows98 \.landing-try-hero > \.relative[\s\S]*background: transparent;[\s\S]*box-shadow: none;/)
  assert.match(source, /Under 20KB/)
  assert.match(source, /Browser-safe/)
  assert.match(source, /One feedback loop/)
  assert.match(source, /Unlimited projects and feedback/)
  assert.match(source, /generateInstallSnippets/)
  assert.match(source, /LandingTryWidgetHero/)
  assert.match(source, /<LandingBackToTop \/>/)
  assert.match(source, /landing-footer border-t px-5 py-5/)
  assert.match(backToTop, /scrollable \* 0\.5/)
  assert.match(backToTop, /aria-label="Back to top"/)
  assert.match(backToTop, /prefers-reduced-motion: reduce/)
  assert.match(css, /\.landing-mascot-context-v2[\s\S]*opacity: 1;[\s\S]*brightness\(1\.08\)/)
  assert.match(css, /\.landing-mascot-inbox \{ right: 0; bottom: 0\.25rem; margin-right: -2\.5rem; \}/)
  assert.match(css, /\.landing-mascot-install \{ right: 0\.75rem; bottom: 3rem; \}/)
  assert.match(css, /\.landing-mascot-faq \{ right: 0; margin-right: -0\.25rem; \}/)
  assert.match(css, /\.landing-footer[\s\S]*background: linear-gradient/)
  assert.match(source, /LandingProductStories/)
  assert.match(source, /LandingVibeInstall/)
  assert.doesNotMatch(source, /WidgetDemo/)
  assert.doesNotMatch(source, /createServerSupabase/)
  assert.doesNotMatch(source, /userbase|Collecting user feedbacks/)
})

test('hosted widget assets are cross-origin compatible and bounded by a short browser cache', () => {
  const nextConfig = read('../../next.config.js')

  assert.match(nextConfig, /source: '\/widget\/:path\*\.js'/)
  assert.match(nextConfig, /key: 'Access-Control-Allow-Origin'[\s\S]*value: '\*'/)
  assert.match(nextConfig, /key: 'Cross-Origin-Resource-Policy'[\s\S]*value: 'cross-origin'/)
  assert.match(nextConfig, /max-age=300, s-maxage=3600, stale-while-revalidate=86400/)
  assert.doesNotMatch(nextConfig, /bodySizeLimit: '10mb'/)
})

test('mascot moments stay contextual across marketing, docs, account, rewards, and guided onboarding', () => {
  const mascot = read('../../src/components/mascot-spotlight.tsx')
  const earlyAccess = read('../../src/app/early-access/page.tsx')
  const programme = read('../../src/app/(dashboard)/early-adopter/page.tsx')
  const docs = read('../../src/app/docs/[[...slug]]/page.tsx')
  const settings = read('../../src/app/(dashboard)/settings/page.tsx')
  const billing = read('../../src/app/(dashboard)/billing/page.tsx')
  const invites = read('../../src/app/(dashboard)/invites/page.tsx')
  const tour = read('../../src/components/product-tour.tsx')
  const css = read('../../src/app/globals.css')

  for (const asset of [
    'early-adopter-host.png',
    'docs-librarian.png',
    'settings-mechanic.png',
    'tour-navigator.png',
    'pro-for-free-gift.png',
    'billing-concierge.png',
  ]) {
    assert.match(mascot, new RegExp(asset.replace('.', '\\.')))
    assert.equal(existsSync(fileURLToPath(new URL(`../../public/mascots-dashboard/${asset}`, import.meta.url))), true)
  }
  assert.match(earlyAccess, /variant="early-adopter"/)
  assert.match(programme, /variant="early-adopter"/)
  assert.match(docs, /variant="docs"/)
  assert.match(settings, /variant="settings"/)
  assert.match(billing, /variant="billing"/)
  assert.match(invites, /variant="pro-for-free"/)
  assert.match(tour, /getTourMascotVariant/)
  assert.match(tour, /target\.includes\('theme'\)/)
  assert.match(tour, /target\.includes\('install'\)/)
  assert.match(css, /mascot-spotlight-idle/)
  assert.match(css, /prefers-reduced-motion: reduce[\s\S]*mascot-spotlight-image/)
  assert.match(css, /windows98 \.mascot-spotlight-image/)
})

test('guided onboarding cannot strand an account on a missing project route', () => {
  const layout = read('../../src/app/(dashboard)/layout.tsx')
  const tour = read('../../src/components/product-tour.tsx')
  const projectSection = read('../../src/app/(dashboard)/projects/[id]/[section]/page.tsx')
  const projectCreation = read('../../src/app/(dashboard)/projects/new/page.tsx')

  assert.match(layout, /projects\?\.find\(\(project\) => project\.id === pathProjectId\)\?\.id/)
  assert.doesNotMatch(layout, /const currentProjectId = projectMatch\?\.\[1\]/)
  assert.match(tour, /Create your first project to continue/)
  assert.match(tour, /saveTutorialProgress\(tutorialId, \{ stepIndex: safeIndex \}\)/)
  assert.match(tour, /Continue guided tour/)
  assert.match(tour, /tourRecovered/)
  assert.match(projectSection, /if \(id === 'new'\) recoverTour\(\)/)
  assert.match(projectSection, /guidedTour=\$\{tutorialId\}&tourStep=\$\{safeStep\}&tourRecovered=missing-project/)
  assert.match(projectCreation, /withTutorialContext/)
  assert.match(projectCreation, /feedbacks:project-created/)
})

test('marketing routes expose a crawlable acquisition foundation without indexing private workspaces', () => {
  const layout = read('../../src/app/layout.tsx')
  const landing = read('../../src/app/page.tsx')
  const robots = read('../../src/app/robots.ts')
  const sitemap = read('../../src/app/sitemap.ts')
  const openGraph = read('../../src/app/opengraph-image.tsx')
  const publicBoard = read('../../src/app/p/[slug]/page.tsx')
  const docs = read('../../src/app/docs/[[...slug]]/page.tsx')
  const llms = read('../../src/app/llms.txt/route.ts')
  const widgetLanding = read('../../src/app/feedback-widget/page.tsx')
  const nextjsLanding = read('../../src/app/feedback-widget/nextjs/page.tsx')
  const comparisonLanding = read('../../src/app/canny-alternative/page.tsx')
  const indexNow = read('../../../../scripts/submit-indexnow.mjs')
  const site = read('../../src/lib/site.ts')

  assert.match(site, /SITE_ORIGIN = 'https:\/\/www\.feedbacks\.dev'/)
  assert.match(layout, /metadataBase: new URL\(SITE_ORIGIN\)/)
  assert.match(landing, /SoftwareApplication/)
  assert.match(landing, /summary_large_image/)
  assert.match(landing, /alternates: \{ canonical: '\/' \}/)
  assert.match(robots, /sitemap: `\$\{SITE_ORIGIN\}\/sitemap\.xml`/)
  assert.match(robots, /'\/dashboard'/)
  assert.match(robots, /'\/api\/'/)
  assert.match(sitemap, /DOCS_PAGES/)
  assert.match(sitemap, /`\$\{SITE_ORIGIN\}\/boards`/)
  assert.match(sitemap, /`\$\{SITE_ORIGIN\}\/feedback-widget`/)
  assert.match(sitemap, /`\$\{SITE_ORIGIN\}\/feedback-widget\/nextjs`/)
  assert.match(sitemap, /`\$\{SITE_ORIGIN\}\/canny-alternative`/)
  assert.match(sitemap, /\.eq\('visibility', 'public'\)/)
  assert.match(sitemap, /\.eq\('directory_opt_in', true\)/)
  assert.match(sitemap, /`\$\{SITE_ORIGIN\}\/p\/\$\{encodeURIComponent\(board\.slug\)\}`/)
  assert.match(publicBoard, /isBoardListedInDirectory\(board\)/)
  assert.match(publicBoard, /index: false, follow: false/)
  assert.match(docs, /alternates: \{ canonical \}/)
  assert.match(llms, /Quickstart:/)
  assert.match(llms, /docs\/operate\/security/)
  assert.match(llms, /docs\/operate\/limits/)
  assert.match(llms, /Content-Type': 'text\/markdown; charset=utf-8'/)
  assert.match(widgetLanding, /FAQPage/)
  assert.match(widgetLanding, /SoftwareApplication/)
  assert.match(nextjsLanding, /HowTo/)
  assert.match(nextjsLanding, /app\/layout\.tsx/)
  assert.match(comparisonLanding, /Canny pricing and plan features/)
  assert.match(comparisonLanding, /Reviewed August 20, 2026/)
  assert.match(indexNow, /api\.indexnow\.org\/indexnow/)
  assert.match(indexNow, /keyLocation/)
  assert.match(openGraph, /ImageResponse/)
  assert.match(openGraph, /Find what users need\./)
  assert.match(landing, /\/early-access/)
})

test('first-run and public feedback screens keep optional work out of the main path', () => {
  const newProject = read('../../src/app/(dashboard)/projects/new/page.tsx')
  const inbox = [
    read('../../src/app/(dashboard)/feedback/page.tsx'),
    read('../../src/app/(dashboard)/feedback/feedback-inbox-client.tsx'),
  ].join('\n')
  const publicForm = read('../../src/components/boards/BoardSubmitForm.tsx')

  assert.match(newProject, /Name your app or website/)
  assert.match(newProject, /Add project details/)
  assert.match(newProject, /Create project and get the snippet/)
  assert.doesNotMatch(newProject, /Choose a different first goal/)
  assert.doesNotMatch(newProject, /What happens next/)
  assert.match(inbox, /Review new messages and move the useful signal forward\./)
  assert.match(inbox, /showMoreFilters/)
  assert.match(publicForm, /What do you need\?/)
  assert.match(publicForm, /className="sr-only"/)
})

test('project creation checks plan limits before writing a project', () => {
  const route = read('../../src/app/api/projects/route.ts')
  const billing = read('../../src/lib/billing.ts')
  const atomicWrites = read('../../src/lib/atomic-quota-writes.ts')
  const migration = read('../../../../sql/063_atomic_free_plan_quota_writes.sql')
  const plans = read('../../../shared/src/plans.ts')

  assert.match(plans, /projectLimit: 2/)
  assert.match(route, /assertCanCreateProject/)
  assert.match(route, /createProjectWithAtomicQuota/)
  assert.match(atomicWrites, /create_project_with_quota/)
  assert.match(migration, /pg_advisory_xact_lock/)
  assert.match(migration, /insert into public\.projects/)
  assert.match(route, /status: 403/)
  assert.match(billing, /project_limit_reached/)
})

test('navigation gives product updates user context instead of an ambiguous release-notes label', () => {
  const sidebar = read('../../src/components/sidebar.tsx')
  const projectHome = read('../../src/app/(dashboard)/projects/[id]/project-home.tsx')
  const updatesOnboarding = read('../../src/components/product-updates/UpdatesOnboarding.tsx')

  assert.match(sidebar, /Updates for users/)
  assert.match(projectHome, /Product updates/)
  assert.match(updatesOnboarding, /useState<Choice>\(["']updates["']\)/)
  assert.doesNotMatch(updatesOnboarding, /localStorage/)
  assert.doesNotMatch(sidebar, /label: 'Release notes'/)
})

test('release note editor exposes recovery and destructive actions without vague page naming', () => {
  const editor = read('../../src/components/product-updates/ProductUpdatesTab.tsx')
  const imageEditor = read('../../src/components/product-updates/ProductUpdateImageEditor.tsx')
  const presentation = read('../../src/components/product-updates/ProductUpdatePresentation.tsx')
  const widgetStyles = read('../../../widget/src/styles.css')
  const input = read('../../src/components/ui/input.tsx')
  const textarea = read('../../src/components/ui/textarea.tsx')

  assert.match(editor, /Edit release note/)
  assert.doesNotMatch(editor, /Edit product update/)
  assert.match(editor, /Reload saved version/)
  assert.match(editor, /Saved version recovery/)
  assert.match(editor, /Editing paused for safety/)
  assert.match(editor, /fixed bottom-/)
  assert.match(editor, /requestWithFreshVersion/)
  assert.match(editor, /recoveredFromConflict/)
  assert.match(editor, /Choose image/)
  assert.match(editor, /Replace image/)
  assert.match(editor, /imageInputRef\.current\?\.click/)
  assert.match(editor, /imageUrl: result\.update\.imageUrl/)
  assert.match(editor, /pendingImagePreviewUrl/)
  assert.match(editor, /Previewing unsaved crop/)
  assert.match(editor, /placeholder="What changed\?"/)
  assert.match(editor, /placeholder="Briefly explain what’s new and why it matters\."/)
  assert.match(imageEditor, /onPreviewChange\(nextPreviewUrl\)/)
  assert.match(imageEditor, /URL\.revokeObjectURL/)
  assert.match(presentation, /release-note-preview-image[\s\S]*className="mt-4 h-auto w-full rounded-md"/)
  assert.doesNotMatch(presentation, /release-note-preview-image[\s\S]*aspect-video/)
  assert.match(widgetStyles, /\.fb-update-image\{[^}]*width:100%;height:auto/)
  assert.doesNotMatch(widgetStyles, /\.fb-update-image\{[^}]*(?:aspect-ratio|object-fit)/)
  assert.match(input, /bg-surface-overlay/)
  assert.match(textarea, /bg-surface-overlay/)
  assert.match(input, /disabled:bg-muted\/60[\s\S]*disabled:opacity-100/)
  assert.match(textarea, /disabled:bg-muted\/60[\s\S]*disabled:opacity-100/)
  assert.match(editor, /Delete release note/)
  assert.match(editor, /Remove image/)
  assert.match(editor, /Editing does not re-announce this release note/)
  assert.match(editor, /Publishing creates this release note&apos;s announcement identity/)
  assert.match(editor, /Save correction/)
  assert.match(editor, /Confirm publish/)
  assert.match(editor, /ProductUpdateVisibilityToggle/)
  assert.match(editor, /hydratedUpdateRef/)
  assert.match(imageEditor, /Drag inside the frame to move it/)
  assert.match(imageEditor, /Resize from top left/)
  assert.match(imageEditor, /resizeProductUpdateCropFromCorner/)
  assert.doesNotMatch(imageEditor, /Horizontal crop position/)
})

test('dashboard mutations preserve mounted content and scope progress to the affected item', () => {
  const updates = read('../../src/components/product-updates/ProductUpdatesTab.tsx')
  const updatesOverview = read('../../src/components/product-updates/ProductUpdatesOverview.tsx')
  const inbox = [
    read('../../src/app/(dashboard)/feedback/page.tsx'),
    read('../../src/app/(dashboard)/feedback/feedback-inbox-client.tsx'),
  ].join('\n')
  const feedbackActions = read('../../src/app/(dashboard)/feedback/[id]/feedback-actions.tsx')
  const projectSettings = read('../../src/app/(dashboard)/projects/[id]/project-tabs.tsx')
  const customize = read('../../src/app/(dashboard)/projects/[id]/customize-tab.tsx')
  const boardSettings = read('../../src/components/board-settings/BoardSettingsTabs.tsx')

  assert.match(updates, /pendingListAction/)
  assert.match(updates, /current\.filter\(\(item\) => item\.id !== update\.id\)/)
  assert.match(updates, /window\.history\.replaceState/)
  assert.match(updatesOverview, /data-pending-action/)
  assert.match(updatesOverview, /aria-busy=\{rowBusy\}/)
  assert.match(updatesOverview, /Delete\?/)
  assert.doesNotMatch(updates, /window\.confirm/)
  assert.match(inbox, /hasLoadedRef/)
  assert.match(inbox, /window\.history\.pushState/)
  assert.match(inbox, /Updating results/)
  assert.doesNotMatch(feedbackActions, /router\.refresh\(/)
  assert.doesNotMatch(projectSettings, /router\.refresh\(/)
  assert.doesNotMatch(customize, /router\.refresh\(/)
  assert.doesNotMatch(boardSettings, /router\.refresh\(/)
})

test('dashboard navigation retains the mounted workspace and uses route prefetching', () => {
  const layout = read('../../src/app/(dashboard)/layout.tsx')
  const sidebar = read('../../src/components/sidebar.tsx')
  const dashboardRoot = new URL('../../src/app/(dashboard)/', import.meta.url)
  const loadingBoundaries = [
    'loading.tsx',
    'api-docs/loading.tsx',
    'billing/loading.tsx',
    'dashboard/boards/loading.tsx',
    'feedback/loading.tsx',
    'feedback/[id]/loading.tsx',
    'integrations/loading.tsx',
    'projects/loading.tsx',
    'projects/new/loading.tsx',
    'projects/[id]/loading.tsx',
    'projects/[id]/verify/loading.tsx',
    'settings/loading.tsx',
  ]

  assert.doesNotMatch(layout, /key=\{pathname\}/)
  assert.match(sidebar, /router\.prefetch\(href\)/)
  assert.doesNotMatch(sidebar, /prefetch=\{false\}/)
  for (const path of loadingBoundaries) {
    assert.equal(existsSync(new URL(path, dashboardRoot)), false, `${path} should not replace mounted dashboard content`)
  }
})

test('feedback form editor refreshes stale baselines and exposes explicit recovery', () => {
  const editor = read('../../src/app/(dashboard)/projects/[id]/customize-tab.tsx')

  assert.match(editor, /loadLatestProject/)
  assert.match(editor, /latestFingerprint === draftFingerprint/)
  assert.match(editor, /latestFingerprint === savedFingerprint/)
  assert.match(editor, /Feedback form already saved/)
  assert.match(editor, /Reload saved settings/)
  assert.match(editor, /The existing host becomes the inline form/)
  assert.match(editor, /Connect feedback to your own button/)
  assert.match(editor, /Trigger selector/)
  assert.match(editor, /No code change needed/)
})

test('dense dashboard forms use clear tonal sections instead of one flat canvas', () => {
  const section = read('../../src/components/ui/workspace-section.tsx')
  const boardIdentity = read('../../src/components/board-settings/BoardIdentitySection.tsx')
  const boardVisibility = read('../../src/components/board-settings/BoardVisibilitySection.tsx')
  const inbox = [
    read('../../src/app/(dashboard)/feedback/page.tsx'),
    read('../../src/app/(dashboard)/feedback/feedback-inbox-client.tsx'),
  ].join('\n')

  assert.match(section, /rounded-lg border bg-card/)
  assert.match(section, /border-b bg-surface-raised\/70/)
  assert.match(boardIdentity, /WorkspaceSection/)
  assert.match(boardVisibility, /WorkspaceSection/)
  assert.match(inbox, /rounded-lg border bg-card/)
})

test('sidebar exposes dashboard and selected-project overview destinations', () => {
  const sidebar = read('../../src/components/sidebar.tsx')

  assert.match(sidebar, /label: 'Dashboard'/)
  assert.match(sidebar, /label: 'Project overview', icon: LayoutDashboard/)
  assert.match(sidebar, /projectTab: 'home'/)
  assert.match(sidebar, /projectTab === 'home'/)
  assert.match(sidebar, /label: 'Collect'/)
  assert.match(sidebar, /label: 'Share with users'/)
  assert.match(sidebar, /label: 'Connect'/)
  assert.match(sidebar, /label: 'My public page'/)
  assert.match(sidebar, /label: 'Feedback form', icon: ClipboardPenLine/)
  assert.match(sidebar, /label: 'Feedback inbox', icon: Inbox/)
  assert.match(sidebar, /label: 'Install & test', icon: Code2/)
  assert.match(sidebar, /project-required\?feature=/)
  assert.match(sidebar, /label: 'Docs', icon: Library/)
  assert.match(sidebar, /label: 'Pro for free', icon: Gift/)
  assert.match(sidebar, /<FolderCog[^>]+\/> Manage projects/)
  assert.doesNotMatch(sidebar, /label: 'Invite friends'/)
  assert.equal(sidebar.match(/label: 'Docs'/g)?.length, 1)
  assert.equal(sidebar.match(/label: 'Pro for free'/g)?.length, 1)
  assert.match(sidebar, /DropdownMenu\.Content/)
  assert.match(sidebar, /Open account menu for/)
  assert.match(sidebar, /Product tour/)
  assert.match(sidebar, /data-feedbacks-trigger/)
  assert.match(sidebar, /Send feedback/)
  assert.match(sidebar, /Sign out/)
  assert.doesNotMatch(sidebar, /Help & account/)
  assert.ok(sidebar.indexOf('aria-controls="mobile-navigation-drawer"') < sidebar.indexOf('<BrandWordmark', sidebar.indexOf('Mobile top bar')))
})

test('authenticated dashboard dogfoods the feedback widget through the account menu', () => {
  const dashboardLayout = read('../../src/app/(dashboard)/layout.tsx')
  const embed = read('../../src/components/feedbacks-widget-script.tsx')
  const sidebar = read('../../src/components/sidebar.tsx')
  const widget = read('../../../widget/src/widget.ts')
  const widgetEntry = read('../../../widget/src/index.ts')

  assert.match(dashboardLayout, /<FeedbacksWidgetScript \/>/)
  assert.match(embed, /fb_pub_eca05612446143cb95127d91753e2a48/)
  assert.match(embed, /https:\/\/app\.feedbacks\.dev\/widget\/latest\.js/)
  assert.match(embed, /data-feedbacks-manual-trigger/)
  assert.match(embed, /strategy="afterInteractive"/)
  assert.match(sidebar, /new CustomEvent\('feedbacks:open'/)
  assert.match(widget, /window\.addEventListener\('feedbacks:open'/)
  assert.match(widget, /if \(this\.manualPresentation\) return/)
  assert.match(widgetEntry, /data-feedbacks-manual-trigger/)
})

test('project management exposes project settings and the confirmed delete flow', () => {
  const projects = read('../../src/app/(dashboard)/projects/page.tsx')
  const projectSettings = read('../../src/app/(dashboard)/projects/[id]/project-tabs.tsx')

  assert.match(projects, /settings#delete-project/)
  assert.match(projects, /<Trash2[^>]+\/>\s*Delete/)
  assert.match(projectSettings, /id="delete-project"/)
  assert.match(projectSettings, /deleteInput !== project\.name/)
  assert.match(projectSettings, /window\.location\.replace\('\/projects'\)/)
})

test('sign-in stays concise while showing the rotating use-case carousel', () => {
  const source = read('../../src/app/auth/page.tsx')
  const carousel = read('../../src/components/auth-use-case-carousel.tsx')

  assert.match(source, /Sign in or create an account/)
  assert.match(source, /handleOAuth\('google'\)/)
  assert.match(source, /GoogleMark/)
  assert.match(source, /Use Google, GitHub, or email/)
  assert.match(source, /Email me a sign-in link/)
  assert.match(source, /New accounts start on the Free plan/)
  assert.match(source, /Back to home/)
  assert.match(source, /SITE_ORIGIN/)
  assert.match(source, /marketingHomeHref/)
  assert.match(source, /<AuthUseCaseCarousel/)
  assert.match(source, /compact displayMode="mobile"/)
  assert.doesNotMatch(source, /Hear what matters/)
  assert.doesNotMatch(source, /Feedback that earns its place/)
  assert.match(carousel, /A user found a bug you cannot reproduce/)
  assert.match(carousel, /Three users asked for the same feature/)
  assert.match(carousel, /Your AI-built app changes every week/)
  assert.doesNotMatch(carousel, /benefits:/)
  assert.doesNotMatch(carousel, /Built for the whole feedback loop/)
  assert.match(carousel, /4_800/)
  assert.match(carousel, /onClickCapture/)
  assert.doesNotMatch(carousel, /onMouseEnter/)
  assert.match(carousel, /Show previous use case/)
  assert.match(carousel, /Show next use case/)
  assert.match(carousel, /Stop automatic story rotation/)
  assert.match(carousel, /Start automatic story rotation/)
  assert.match(carousel, /visibilitychange/)
  assert.match(carousel, /aria-roledescription="slide"/)
  assert.match(carousel, /auth-card-signal/)
  assert.match(carousel, /prefers-reduced-motion/)
  assert.doesNotMatch(source, /data-api-url/)
})

test('marketing hero and workspace states share the new motion and texture language', () => {
  const css = read('../../src/app/globals.css')
  const landing = read('../../src/app/page.tsx')
  const emptyState = read('../../src/components/ui/empty-state.tsx')
  const layout = read('../../src/app/(dashboard)/layout.tsx')

  assert.match(css, /--ease-spring:/)
  assert.match(css, /@keyframes hero-color-breathe/)
  assert.match(css, /\.landing-section-warm,[\s\S]*\.landing-section-aurora\s*\{\s*background-color: oklch\(0\.972 0\.01 105\)/)
  assert.match(css, /--surface-grain:/)
  assert.match(css, /--landing-premium-section:/)
  assert.match(css, /--landing-slate-section:/)
  assert.match(css, /\.landing-try-hero,[\s\S]*\.landing-faq-section[\s\S]*background: var\(--landing-premium-section\)/)
  assert.match(css, /\.landing-journey,[\s\S]*\.landing-final-cta[\s\S]*background: var\(--landing-slate-section\)/)
  assert.match(css, /\.marketing-shell \.landing-install-shell[\s\S]*linear-gradient\(145deg, oklch\(0\.17 0\.018 145\)/)
  assert.match(css, /\.landing-section-mascot[\s\S]*max-width: calc\(100vw - 2rem\)/)
  assert.doesNotMatch(css, /\.landing-mascot-(?:journey|context-v2|inbox|loop|install|proof|pricing|faq|final)[^{]*\{[^}]*(?:^|;)\s*(?:left|right|top):\s*-/m)
  assert.match(css, /@keyframes landing-final-chip-drift/)
  assert.match(css, /\.landing-final-chip-top-right/)
  assert.match(css, /\.landing-final-chip-bottom-left/)
  assert.match(landing, /landing-free-plan relative flex h-full flex-col/)
  assert.match(landing, /landing-pro-plan relative flex h-full flex-col/)
  assert.equal(landing.match(/mt-auto block pt-8/g)?.length, 2)
  assert.match(landing, /Reproduced · suspiciously fast/)
  assert.match(landing, /Fix shipped · meeting avoided/)
  assert.match(css, /surface-film-grain/)
  assert.match(css, /baseFrequency='\.72'/)
  assert.match(css, /stitchTiles='stitch'/)
  assert.match(css, /background-size: 192px 192px/)
  assert.doesNotMatch(css, /--particle-grain:/)
  assert.match(css, /\.windows98 \.landing-hero-grain::after/)
  assert.match(css, /\.windows98 \.auth-form-pane::after/)
  assert.match(css, /content: none/)
  assert.match(css, /\.landing-section > div/)
  assert.match(css, /\.dark \.landing-section::after/)
  assert.match(css, /\.auth-story-pane::after/)
  assert.match(css, /\.dark \.auth-story-pane::after/)
  assert.match(css, /html:not\(\.dark\):not\(\.windows98\) \.auth-form-pane/)
  assert.match(css, /linear-gradient\(138deg, #fffef9 0%, #faf8f1 48%, #f2efe7 100%\)/)
  assert.match(css, /mix-blend-mode: soft-light/)
  assert.match(css, /\.auth-card-signal-disc/)
  assert.match(css, /\.workspace-route-enter/)
  assert.match(css, /prefers-reduced-motion/)
  assert.match(emptyState, /workspace-empty-state/)
  assert.doesNotMatch(layout, /key=\{pathname\}/)
})

test('settings reuses a private system project for product feedback and updates', () => {
  const settings = read('../../src/app/(dashboard)/settings/page.tsx')
  const panel = read('../../src/components/product-feedback-panel.tsx')
  const route = read('../../src/app/api/product-feedback/route.ts')
  const migration = read('../../../../sql/058_internal_product_feedback_project.sql')

  assert.match(settings, /<ProductFeedbackPanel/)
  assert.match(panel, /Suggestion/)
  assert.match(panel, /Problem/)
  assert.match(panel, /Updates from us/)
  assert.match(route, /getUser\(\)/)
  assert.match(route, /checkRateLimit\(request, 'product-feedback', 5, 10, user\.id\)/)
  assert.match(route, /is_public: false/)
  assert.match(route, /\.eq\('status', 'published'\)/)
  assert.match(migration, /drsyedirfan93@gmail\.com/i)
  assert.match(migration, /internal_feedback_project', true/i)
  assert.match(migration, /api_key,\s+api_key_hash,\s+api_key_last_four/i)
})

test('downgraded accounts keep runtime feature limits, not just dashboard gates', () => {
  const feedbackRoute = read('../../src/app/api/feedback/route.ts')
  const v1Route = read('../../src/app/api/v1/feedback/route.ts')
  const delivery = read('../../src/lib/webhook-delivery.ts')
  const bootstrap = read('../../src/app/api/widget/bootstrap/route.ts')
  const updates = read('../../src/app/api/widget/updates/route.ts')

  assert.match(feedbackRoute, /webhookEndpointLimit/)
  assert.match(v1Route, /webhookEndpointLimit/)
  assert.match(delivery, /endpointLimit/)
  assert.match(delivery, /enabledEndpointCount < endpointLimit/)
  assert.match(bootstrap, /productUpdateActiveLimit/)
  assert.match(updates, /productUpdateActiveLimit/)
})

test('widget attribution is conspicuous, linked, and controlled by server entitlements', () => {
  const widget = read('../../../widget/src/widget.ts')
  const styles = read('../../../widget/src/styles.css')
  const bootstrap = read('../../src/app/api/widget/bootstrap/route.ts')

  assert.match(widget, /https:\/\/www\.feedbacks\.dev\/\?utm_source=widget&utm_medium=powered_by/)
  assert.match(widget, /rel="noopener noreferrer"/)
  assert.match(styles, /\.fb-powered span \{[\s\S]*font-weight: 600/)
  assert.match(styles, /\.fb-powered a \{[\s\S]*color: var\(--fb-primary/)
  assert.match(styles, /font-weight: 800/)
  assert.match(bootstrap, /showPoweredBy: !billing\.entitlements\.customBranding/)
})

test('theme tokens use perceptual OKLCH colors in both themes', () => {
  const css = read('../../src/app/globals.css')
  const tailwind = read('../../tailwind.config.cjs')

  assert.match(css, /--background: 0\.968/)
  assert.match(css, /\.dark[\s\S]*--background: 0\.115/)
  assert.match(css, /\.dark[\s\S]*--surface-raised: 0\.305/)
  assert.match(css, /\.dark[\s\S]*--surface-soft: 0\.255/)
  assert.match(css, /\.dark[\s\S]*--surface-inset: 0\.165/)
  assert.match(css, /\.dark[\s\S]*--card: 0\.225/)
  assert.match(css, /\[class~="shadow-\[var\(--shadow-card\)\]"\]/)
  assert.match(css, /--surface-sidebar:/)
  assert.match(css, /--surface-selected:/)
  assert.match(css, /--surface-code-foreground:/)
  assert.match(tailwind, /surface:\s*\{/)
  assert.match(tailwind, /'code-foreground':\s*'oklch\(var\(--surface-code-foreground\)/)
  assert.match(tailwind, /oklch\(var\(--primary\)/)
  assert.doesNotMatch(tailwind, /hsl\(var\(--primary\)/)
})

test('Windows 98 is a complete selectable appearance across product and public surfaces', () => {
  const css = read('../../src/app/globals.css')
  const layout = read('../../src/app/layout.tsx')
  const toggle = read('../../src/components/theme-toggle.tsx')
  const publicControl = read('../../src/components/public-theme-control.tsx')
  const appearance = read('../../src/lib/appearance.ts')
  const landing = read('../../src/app/page.tsx')
  const landingStory = read('../../src/components/landing-feedback-story.tsx')
  const settings = read('../../src/app/(dashboard)/settings/page.tsx')

  assert.match(layout, /themes=\{\['light', 'dark', 'windows98'\]\}/)
  assert.match(layout, /defaultTheme="system"/)
  assert.match(layout, /appearanceSyncScript/)
  assert.match(layout, /localStorage\.setItem\('theme'/)
  assert.match(appearance, /APPEARANCE_COOKIE_NAME = 'feedbacks-theme'/)
  assert.match(appearance, /'light', 'dark', 'windows98', 'system'/)
  assert.match(appearance, /Domain=\.feedbacks\.dev/)
  assert.match(appearance, /persistSharedAppearance/)
  assert.match(toggle, /persistSharedAppearance\(nextTheme\)/)
  assert.match(settings, /persistSharedAppearance\(value\)/)
  assert.match(toggle, /value: 'windows98', label: 'Windows 98'/)
  assert.match(toggle, /role="radiogroup"/)
  assert.match(toggle, /p-0\.5 shadow-sm sm:p-1/)
  assert.match(toggle, /h-8 min-w-8[\s\S]*sm:h-10 sm:min-w-10/)
  assert.match(settings, /\['windows98', 'Windows 98'\]/)
  assert.match(publicControl, /<ThemeToggle collapsed \/>/)
  assert.match(publicControl, /pathname === '\/auth'/)
  assert.match(publicControl, /auth-theme-control/)
  assert.match(publicControl, /<ThemeToggle landing \/>/)
  assert.match(publicControl, /pathname === '\/'/)
  assert.match(landing, /<ThemeToggle landing \/>/)
  assert.match(toggle, /option\.value !== 'system'/)
  assert.match(toggle, /landing-theme-option-98/)
  assert.match(toggle, /function Windows98Mark/)
  assert.match(toggle, />Windows<\/span>/)
  assert.match(toggle, />98<\/span>/)
  assert.equal(toggle.match(/<Windows98Mark \/>/g)?.length, 3)
  assert.match(landingStory, /landing-story-step-label/)
  assert.match(css, /\.windows98 \.landing-story-step-label/)
  assert.match(css, /\.windows98 \.landing-demo-tab-label/)
  assert.match(css, /\.windows98 \.landing-demo-tab-detail/)
  assert.match(css, /\.windows98 \.landing-demo-tab-icon-active/)
  assert.match(css, /@keyframes landing-theme-98-shine/)
  assert.match(css, /\.windows98 \{/)
  assert.match(css, /--win98-raised:/)
  assert.match(css, /\.windows98 \.dashboard-shell/)
  assert.match(css, /\.windows98 \.landing-hero/)
  assert.match(css, /\.windows98 \.docs-content/)
  assert.match(css, /\.windows98 \.public-board-shell/)
  assert.match(css, /\.windows98 input/)
  assert.match(css, /\.windows98 table/)
})

test('authenticated workspaces use page headers, section panels, and progressive disclosure', () => {
  const card = read('../../src/components/ui/card.tsx')
  const install = read('../../src/app/(dashboard)/projects/[id]/install-tab.tsx')
  const projectHome = read('../../src/app/(dashboard)/projects/[id]/project-home.tsx')
  const customize = read('../../src/app/(dashboard)/projects/[id]/customize-tab.tsx')
  const verify = read('../../src/app/(dashboard)/projects/[id]/project-verify-client.tsx')

  assert.match(card, /rounded-lg border border-border bg-card/)
  assert.match(card, /border-b bg-surface-raised\/70/)
  assert.match(card, /shadow-\[var\(--shadow-card\)\]/)
  assert.match(install, /title="Choose your stack"/)
  assert.match(install, /dataTour="install-snippet"/)
  assert.match(install, /bg-surface-inset/)
  assert.match(install, /bg-surface-soft/)
  assert.match(install, /bg-surface-selected/)
  assert.match(install, /Connection details/)
  assert.match(projectHome, /<PageHeader/)
  assert.match(projectHome, /<SectionPanel/)
  assert.match(customize, /Optional fields and protection/)
  assert.match(verify, /<PageHeader/)
})

test('public docs use the stable canonical embed and remote customization language', () => {
  const source = read('../../src/lib/docs-content.ts')

  assert.match(source, /data-feedbacks-host/)
  assert.match(source, /data-project=/)
  assert.match(source, /Customize remotely/)
  assert.match(source, /installed snippet stays stable/)
  assert.doesNotMatch(source, /data-api-url/)
  assert.doesNotMatch(source, /data-config-version/)
})

test('dashboard MCP setup emits a valid project-scoped client configuration', () => {
  const apiDocs = read('../../src/app/(dashboard)/projects/[id]/api-docs.tsx')

  assert.match(apiDocs, /"mcpServers": \{/)
  assert.match(apiDocs, /"feedbacks": \{/)
  assert.match(apiDocs, /"type": "stdio"/)
  assert.match(apiDocs, /FEEDBACKS_API_KEY/)
  assert.match(apiDocs, /FEEDBACKS_API_URL/)
})

test('public board directory owns a main landmark without nesting one in the dashboard', () => {
  const directorySurface = read('../../src/app/boards/board-directory-surface.tsx')

  assert.match(directorySurface, /const Root = dashboard \? 'div' : 'main'/)
  assert.match(directorySurface, /<Root/)
  assert.match(directorySurface, /<\/Root>/)
})

test('forms identify failed fields and public interactions avoid blocking browser alerts', () => {
  const input = read('../../src/components/ui/input.tsx')
  const textarea = read('../../src/components/ui/textarea.tsx')
  const newProject = read('../../src/app/(dashboard)/projects/new/page.tsx')
  const projectRoute = read('../../src/app/api/projects/route.ts')
  const boardSubmit = read('../../src/components/boards/BoardSubmitForm.tsx')
  const boardSubmitRoute = read('../../src/app/api/boards/[slug]/submit/route.ts')
  const publicBoard = read('../../src/app/p/[slug]/public-board.tsx')

  assert.match(input, /aria-\[invalid=true\]:border-destructive/)
  assert.match(textarea, /aria-\[invalid=true\]:border-destructive/)
  assert.match(newProject, /project-name-error/)
  assert.match(projectRoute, /fieldErrors: \{ name:/)
  assert.match(boardSubmit, /board-post-email-error/)
  assert.match(boardSubmitRoute, /fieldErrors: \{ email:/)
  assert.doesNotMatch(publicBoard, /window\.alert/)
  assert.match(publicBoard, /aria-live="assertive"/)
})
