import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('landing page explains both sides of the feedback loop and keeps the install-once architecture', () => {
  const source = read('../../src/app/page.tsx')
  const demo = read('../../src/components/landing-hero-demo.tsx')
  const install = read('../../src/components/landing-install-story.tsx')
  const feedback = read('../../src/components/landing-feedback-story.tsx')
  const connections = read('../../src/components/landing-connections-story.tsx')

  assert.match(source, /Find what users need\./)
  assert.match(source, /Show what you fixed\./)
  assert.match(source, /Add a lightweight feedback widget to your app/)
  assert.match(source, /Every message reaches one focused inbox/)
  assert.match(source, /Copy\. Verify\. Start listening\./)
  assert.match(source, /Customize after the connection works\./)
  assert.match(source, /Public in the browser\. Private on the server\./)
  assert.match(source, /Questions developers ask first\./)
  assert.match(source, /Under 20KB gzip/)
  assert.match(source, /Private feedback media/)
  assert.match(source, /Install in under 10 minutes/)
  assert.match(demo, /Orbit/)
  assert.match(demo, /Paste one snippet/)
  assert.match(demo, /User sends context/)
  assert.match(demo, /Your team acts/)
  assert.match(demo, /User sees the fix/)
  assert.match(demo, /Screenshot/)
  assert.match(demo, /prefers-reduced-motion/)
  assert.doesNotMatch(demo, /setInterval/)
  assert.match(demo, /setTimeout/)
  assert.match(install, /Copy the snippet/)
  assert.match(install, /Send one test/)
  assert.match(install, /Customize later/)
  assert.match(install, /No private credential enters the browser/)
  assert.match(feedback, /A user tells you/)
  assert.match(feedback, /Your team fixes it/)
  assert.match(feedback, /Users see the fix/)
  assert.match(connections, /Slack/)
  assert.match(connections, /GitHub/)
  assert.match(connections, /Discord/)
  assert.match(connections, /API or MCP/)
  assert.match(connections, /public ideas page/i)
  assert.match(source, /More projects and feedback/)
  assert.doesNotMatch(source, /Unlimited projects/)
  assert.match(source, /generateInstallSnippets/)
  assert.match(source, /LandingHeroDemo/)
  assert.match(source, /LandingFeedbackStory/)
  assert.match(source, /LandingInstallStory/)
  assert.doesNotMatch(source, /WidgetDemo/)
  assert.doesNotMatch(source, /createServerSupabase/)
  assert.doesNotMatch(source, /userbase|Collecting user feedbacks/)
})

test('marketing routes expose a crawlable acquisition foundation without indexing private workspaces', () => {
  const layout = read('../../src/app/layout.tsx')
  const landing = read('../../src/app/page.tsx')
  const robots = read('../../src/app/robots.ts')
  const sitemap = read('../../src/app/sitemap.ts')
  const openGraph = read('../../src/app/opengraph-image.tsx')
  const site = read('../../src/lib/site.ts')

  assert.match(site, /SITE_ORIGIN = 'https:\/\/www\.feedbacks\.dev'/)
  assert.match(layout, /metadataBase: new URL\(SITE_ORIGIN\)/)
  assert.match(landing, /SoftwareApplication/)
  assert.match(landing, /summary_large_image/)
  assert.match(landing, /alternates: \{ canonical: '\/' \}/)
  assert.match(robots, /sitemap: `\$\{SITE_ORIGIN\}\/sitemap\.xml`/)
  assert.match(robots, /'\/dashboard'/)
  assert.match(robots, /'\/api\/'/)
  assert.match(sitemap, /DOCS_PAGES/)
  assert.match(sitemap, /`\$\{SITE_ORIGIN\}\/boards`/)
  assert.match(openGraph, /ImageResponse/)
  assert.match(openGraph, /Find what users need\./)
  assert.match(landing, /\/early-access/)
})

test('first-run and public feedback screens keep optional work out of the main path', () => {
  const newProject = read('../../src/app/(dashboard)/projects/new/page.tsx')
  const inbox = read('../../src/app/(dashboard)/feedback/page.tsx')
  const publicForm = read('../../src/components/boards/BoardSubmitForm.tsx')

  assert.match(newProject, /Name your app or website/)
  assert.match(newProject, /Add project details/)
  assert.match(newProject, /Create project and get the snippet/)
  assert.doesNotMatch(newProject, /Choose a different first goal/)
  assert.doesNotMatch(newProject, /What happens next/)
  assert.match(inbox, /Review new messages and move the useful signal forward\./)
  assert.match(inbox, /showMoreFilters/)
  assert.match(publicForm, /What do you need\?/)
  assert.match(publicForm, /className="sr-only"/)
})

test('project creation checks plan limits before writing a project', () => {
  const route = read('../../src/app/api/projects/route.ts')
  const billing = read('../../src/lib/billing.ts')
  const plans = read('../../../shared/src/plans.ts')

  assert.match(plans, /projectLimit: 2/)
  assert.match(route, /assertCanCreateProject/)
  assert.ok(route.indexOf('assertCanCreateProject') < route.indexOf("from('projects').insert"))
  assert.match(route, /status: 403/)
  assert.match(billing, /project_limit_reached/)
})

test('navigation gives product updates user context instead of an ambiguous release-notes label', () => {
  const sidebar = read('../../src/components/sidebar.tsx')
  const projectHome = read('../../src/app/(dashboard)/projects/[id]/project-home.tsx')
  const updatesOnboarding = read('../../src/components/product-updates/UpdatesOnboarding.tsx')

  assert.match(sidebar, /Updates for users/)
  assert.match(projectHome, /Product updates/)
  assert.match(updatesOnboarding, /useState<Choice>\(["']updates["']\)/)
  assert.doesNotMatch(updatesOnboarding, /localStorage/)
  assert.doesNotMatch(sidebar, /label: 'Release notes'/)
})

test('dense dashboard forms use clear tonal sections instead of one flat canvas', () => {
  const section = read('../../src/components/ui/workspace-section.tsx')
  const boardIdentity = read('../../src/components/board-settings/BoardIdentitySection.tsx')
  const boardVisibility = read('../../src/components/board-settings/BoardVisibilitySection.tsx')
  const inbox = read('../../src/app/(dashboard)/feedback/page.tsx')

  assert.match(section, /rounded-lg border bg-card/)
  assert.match(section, /border-b bg-surface-raised\/70/)
  assert.match(boardIdentity, /WorkspaceSection/)
  assert.match(boardVisibility, /WorkspaceSection/)
  assert.match(inbox, /rounded-lg border bg-card/)
})

test('sidebar exposes a stable Home destination and groups project work by user intent', () => {
  const sidebar = read('../../src/components/sidebar.tsx')

  assert.match(sidebar, /label: 'Home'/)
  assert.match(sidebar, /label: 'Collect'/)
  assert.match(sidebar, /label: 'Share with users'/)
  assert.match(sidebar, /label: 'Connect'/)
  assert.match(sidebar, /Public feedback board/)
  assert.match(sidebar, /label: 'Feedback form', icon: ClipboardPenLine/)
  assert.match(sidebar, /label: 'Feedback inbox', icon: Inbox/)
  assert.doesNotMatch(sidebar, /label: 'Overview'/)
  assert.doesNotMatch(sidebar, /projectTab: 'home'/)
  assert.match(sidebar, /project-required\?feature=/)
  assert.match(sidebar, /label: 'Invite friends'/)
  assert.ok(sidebar.indexOf('aria-controls="mobile-navigation-drawer"') < sidebar.indexOf('<BrandWordmark', sidebar.indexOf('Mobile top bar')))
})

test('sign-in explains account creation and the shared embed before setup', () => {
  const source = read('../../src/app/auth/page.tsx')

  assert.match(source, /Sign in or create an account/)
  assert.match(source, /GitHub or a magic link creates your account/)
  assert.match(source, /One embed for both/)
  assert.doesNotMatch(source, /data-api-url/)
})

test('theme tokens use perceptual OKLCH colors in both themes', () => {
  const css = read('../../src/app/globals.css')
  const tailwind = read('../../tailwind.config.cjs')

  assert.match(css, /--background: 0\.968/)
  assert.match(css, /\.dark[\s\S]*--background: 0\.115/)
  assert.match(css, /\.dark[\s\S]*--surface-raised: 0\.305/)
  assert.match(css, /\.dark[\s\S]*--surface-soft: 0\.255/)
  assert.match(css, /\.dark[\s\S]*--surface-inset: 0\.165/)
  assert.match(css, /\.dark[\s\S]*--card: 0\.225/)
  assert.match(css, /\[class~="shadow-\[var\(--shadow-card\)\]"\]/)
  assert.match(css, /--surface-sidebar:/)
  assert.match(css, /--surface-selected:/)
  assert.match(tailwind, /surface:\s*\{/)
  assert.match(tailwind, /oklch\(var\(--primary\)/)
  assert.doesNotMatch(tailwind, /hsl\(var\(--primary\)/)
})

test('Windows 98 is a complete selectable appearance across product and public surfaces', () => {
  const css = read('../../src/app/globals.css')
  const layout = read('../../src/app/layout.tsx')
  const toggle = read('../../src/components/theme-toggle.tsx')
  const publicControl = read('../../src/components/public-theme-control.tsx')
  const landing = read('../../src/app/page.tsx')
  const landingStory = read('../../src/components/landing-feedback-story.tsx')
  const settings = read('../../src/app/(dashboard)/settings/page.tsx')

  assert.match(layout, /themes=\{\['light', 'dark', 'windows98'\]\}/)
  assert.match(layout, /defaultTheme="system"/)
  assert.match(toggle, /value: 'windows98', label: 'Windows 98'/)
  assert.match(toggle, /role="radiogroup"/)
  assert.match(settings, /\['windows98', 'Windows 98'\]/)
  assert.match(publicControl, /<ThemeToggle collapsed \/>/)
  assert.match(publicControl, /pathname === '\/'/)
  assert.match(landing, /<ThemeToggle landing \/>/)
  assert.match(toggle, /option\.value !== 'system'/)
  assert.match(toggle, /landing-theme-option-98/)
  assert.match(landingStory, /landing-story-step-label/)
  assert.match(css, /\.windows98 \.landing-story-step-label/)
  assert.match(css, /@keyframes landing-theme-98-shine/)
  assert.match(css, /\.windows98 \{/)
  assert.match(css, /--win98-raised:/)
  assert.match(css, /\.windows98 \.dashboard-shell/)
  assert.match(css, /\.windows98 \.landing-hero/)
  assert.match(css, /\.windows98 \.docs-content/)
  assert.match(css, /\.windows98 \.public-board-shell/)
  assert.match(css, /\.windows98 input/)
  assert.match(css, /\.windows98 table/)
})

test('authenticated workspaces use page headers, section panels, and progressive disclosure', () => {
  const card = read('../../src/components/ui/card.tsx')
  const install = read('../../src/app/(dashboard)/projects/[id]/install-tab.tsx')
  const projectHome = read('../../src/app/(dashboard)/projects/[id]/project-home.tsx')
  const customize = read('../../src/app/(dashboard)/projects/[id]/customize-tab.tsx')
  const verify = read('../../src/app/(dashboard)/projects/[id]/project-verify-client.tsx')

  assert.match(card, /rounded-lg border border-border bg-card/)
  assert.match(card, /border-b bg-surface-raised\/70/)
  assert.match(card, /shadow-\[var\(--shadow-card\)\]/)
  assert.match(install, /title="Choose your stack"/)
  assert.match(install, /dataTour="install-snippet"/)
  assert.match(install, /bg-surface-inset/)
  assert.match(install, /bg-surface-soft/)
  assert.match(install, /bg-surface-selected/)
  assert.match(install, /Connection details/)
  assert.match(projectHome, /<PageHeader/)
  assert.match(projectHome, /<SectionPanel/)
  assert.match(customize, /Optional fields and protection/)
  assert.match(verify, /<PageHeader/)
})

test('public docs use the stable canonical embed and remote customization language', () => {
  const source = read('../../src/lib/docs-content.ts')

  assert.match(source, /data-feedbacks-host/)
  assert.match(source, /data-project=/)
  assert.match(source, /Customize remotely/)
  assert.match(source, /installed snippet stays stable/)
  assert.doesNotMatch(source, /data-api-url/)
  assert.doesNotMatch(source, /data-config-version/)
})

test('public board directory owns a main landmark without nesting one in the dashboard', () => {
  const directorySurface = read('../../src/app/boards/board-directory-surface.tsx')

  assert.match(directorySurface, /const Root = dashboard \? 'div' : 'main'/)
  assert.match(directorySurface, /<Root/)
  assert.match(directorySurface, /<\/Root>/)
})

test('forms identify failed fields and public interactions avoid blocking browser alerts', () => {
  const input = read('../../src/components/ui/input.tsx')
  const textarea = read('../../src/components/ui/textarea.tsx')
  const newProject = read('../../src/app/(dashboard)/projects/new/page.tsx')
  const projectRoute = read('../../src/app/api/projects/route.ts')
  const boardSubmit = read('../../src/components/boards/BoardSubmitForm.tsx')
  const boardSubmitRoute = read('../../src/app/api/boards/[slug]/submit/route.ts')
  const publicBoard = read('../../src/app/p/[slug]/public-board.tsx')

  assert.match(input, /aria-\[invalid=true\]:border-destructive/)
  assert.match(textarea, /aria-\[invalid=true\]:border-destructive/)
  assert.match(newProject, /project-name-error/)
  assert.match(projectRoute, /fieldErrors: \{ name:/)
  assert.match(boardSubmit, /board-post-email-error/)
  assert.match(boardSubmitRoute, /fieldErrors: \{ email:/)
  assert.doesNotMatch(publicBoard, /window\.alert/)
  assert.match(publicBoard, /aria-live="assertive"/)
})
