'use client'

import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { toast } from '@/hooks/use-toast'

type Update = { id: string; status: 'draft' | 'published' | 'archived'; version_label: string | null; title: string; summary: string; highlights: string[]; cta_label: string | null; cta_url: string | null; published_at: string | null; metrics: { impressions: number; dismissals: number; ctaClicks: number } }
type Settings = { enabled: boolean; autoShow: boolean; displayDelayMs: number; theme: 'auto' | 'light' | 'dark'; accentColor: string; includePaths: string[]; excludePaths: string[]; showPoweredBy: boolean }
const empty = { title: '', summary: '', versionLabel: '', highlights: '', ctaLabel: '', ctaUrl: '' }

export function ProductUpdatesTab({ projectId }: { projectId: string }) {
  const [updates, setUpdates] = React.useState<Update[]>([]); const [settings, setSettings] = React.useState<Settings | null>(null)
  const [form, setForm] = React.useState(empty); const [loading, setLoading] = React.useState(true); const [saving, setSaving] = React.useState(false)
  const load = React.useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/projects/${projectId}/updates`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setUpdates(data.updates || []); setSettings(data.settings) } catch (error) { toast({ title: 'Could not load Product Updates', description: error instanceof Error ? error.message : 'Try again.', variant: 'destructive' }) } finally { setLoading(false) } }, [projectId])
  React.useEffect(() => { void load() }, [load])
  async function createDraft() {
    setSaving(true); try { const response = await fetch(`/api/projects/${projectId}/updates`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ versionLabel: form.versionLabel, title: form.title, summary: form.summary, highlights: form.highlights.split('\n').map((value) => value.trim()).filter(Boolean), ctaLabel: form.ctaLabel, ctaUrl: form.ctaUrl }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || Object.values(data.errors || {}).join(' ')); setForm(empty); toast({ title: 'Draft saved' }); await load() } catch (error) { toast({ title: 'Could not save draft', description: error instanceof Error ? error.message : 'Check the fields and try again.', variant: 'destructive' }) } finally { setSaving(false) }
  }
  async function action(update: Update, name: 'publish' | 'archive' | 'restore' | 'delete') { const response = await fetch(`/api/projects/${projectId}/updates/${update.id}${name === 'delete' ? '' : `/${name}`}`, { method: name === 'delete' ? 'DELETE' : 'POST', headers: { 'Content-Type': 'application/json' }, body: name === 'publish' ? JSON.stringify({}) : undefined }); if (!response.ok) { const data = await response.json().catch(() => null); toast({ title: `Could not ${name} update`, description: data?.error || 'Try again.', variant: 'destructive' }); return } await load() }
  async function saveSettings(next: Settings) { const response = await fetch(`/api/projects/${projectId}/updates/settings`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); const data = await response.json(); if (!response.ok) { toast({ title: 'Could not save settings', description: data.error || 'Try again.', variant: 'destructive' }); return } setSettings(data); toast({ title: 'Product Update settings saved' }) }
  if (loading) return <Card><CardContent className="p-6 text-sm text-muted-foreground">Loading Product Updates…</CardContent></Card>
  return <div className="space-y-6">
    <Card><CardHeader><CardTitle>Tell users what just shipped</CardTitle><CardDescription>Publish a short update and show it once inside your product through the widget you already installed.</CardDescription></CardHeader><CardContent className="space-y-4">
      {!settings?.enabled && <p className="rounded-md border border-amber-500/30 bg-amber-500/10 p-3 text-sm">Enable this feature here and add <code>enableUpdates</code> in Customize once. Future publications are remote.</p>}
      {settings && <div className="grid gap-3 md:grid-cols-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.enabled} onChange={(event) => { const next = { ...settings, enabled: event.target.checked }; setSettings(next); void saveSettings(next) }} /> Enable Product Updates</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.autoShow} onChange={(event) => { const next = { ...settings, autoShow: event.target.checked }; setSettings(next); void saveSettings(next) }} /> Auto-show newest unseen</label><label className="text-sm">Delay (ms)<Input type="number" min="0" max="30000" value={settings.displayDelayMs} onChange={(event) => setSettings({ ...settings, displayDelayMs: Number(event.target.value) || 0 })} onBlur={() => void saveSettings(settings)} /></label></div>}
    </CardContent></Card>
    <Card><CardHeader><CardTitle>New update</CardTitle><CardDescription>Structured plain text only. Existing viewers will not automatically see edits to a live update.</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><div className="space-y-3"><Label>Version label <Input value={form.versionLabel} maxLength={32} onChange={(event) => setForm({ ...form, versionLabel: event.target.value })} placeholder="v2.4" /></Label><Label>Title <Input value={form.title} maxLength={120} onChange={(event) => setForm({ ...form, title: event.target.value })} /></Label><Label>Summary <Textarea value={form.summary} maxLength={280} onChange={(event) => setForm({ ...form, summary: event.target.value })} /></Label><Label>Highlights (one per line)<Textarea value={form.highlights} onChange={(event) => setForm({ ...form, highlights: event.target.value })} /></Label><Label>CTA label <Input value={form.ctaLabel} maxLength={40} onChange={(event) => setForm({ ...form, ctaLabel: event.target.value })} /></Label><Label>CTA URL <Input value={form.ctaUrl} maxLength={2048} onChange={(event) => setForm({ ...form, ctaUrl: event.target.value })} placeholder="/new-feature" /></Label><Button onClick={() => void createDraft()} disabled={saving}>{saving ? 'Saving…' : 'Save draft'}</Button></div><div className="rounded-xl border bg-muted/20 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">What’s New</p>{form.versionLabel && <p className="mt-4 text-xs font-semibold text-primary">{form.versionLabel}</p>}<h3 className="mt-2 text-xl font-semibold">{form.title || 'Your update title'}</h3><p className="mt-2 text-sm text-muted-foreground">{form.summary || 'A concise summary appears here.'}</p>{form.highlights && <ul className="mt-4 list-disc space-y-1 pl-5 text-sm">{form.highlights.split('\n').filter(Boolean).map((item) => <li key={item}>{item}</li>)}</ul>}{form.ctaLabel && <Button className="mt-5" size="sm">{form.ctaLabel}</Button>}</div></CardContent></Card>
    <Card><CardHeader><CardTitle>Updates</CardTitle><CardDescription>Metrics are approximate daily aggregates.</CardDescription></CardHeader><CardContent className="space-y-3">{updates.length === 0 ? <p className="text-sm text-muted-foreground">No updates yet. Create your first draft above.</p> : updates.map((update) => <div key={update.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-medium">{update.version_label ? `${update.version_label} · ` : ''}{update.title}</p><p className="text-sm text-muted-foreground">{update.status} · {update.metrics.impressions} impressions · {update.metrics.ctaClicks} CTA clicks</p></div><div className="flex gap-2">{update.status === 'draft' && <Button size="sm" onClick={() => void action(update, 'publish')}>Publish now</Button>}{update.status === 'published' && <Button size="sm" variant="outline" onClick={() => void action(update, 'archive')}>Archive</Button>}{update.status === 'archived' && <Button size="sm" variant="outline" onClick={() => void action(update, 'restore')}>Restore to draft</Button>}<Button size="sm" variant="ghost" onClick={() => void action(update, 'delete')}>Delete</Button></div></div>)}</CardContent></Card>
  </div>
}
